create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text unique not null,
  phone text,
  role text not null default 'customer' check (role in ('customer', 'manager')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_code text unique not null,
  customer_id uuid not null references auth.users(id) on delete cascade,
  customer_name text,
  items jsonb not null,
  subtotal numeric(10, 2) not null default 0,
  tax numeric(10, 2) not null default 0,
  total numeric(10, 2) not null,
  currency text not null default 'UZS',
  status text not null default 'Placed',
  order_type text not null check (order_type in ('Dine In', 'Takeaway')),
  table_number integer,
  guest_count integer,
  pickup_name text,
  pickup_time text,
  payment_method text,
  payment_status text,
  payment_reference text,
  special_request text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders enable row level security;

drop policy if exists "orders_select_own_or_manager" on public.orders;
create policy "orders_select_own_or_manager"
on public.orders for select
using (
  auth.uid() = customer_id
  or exists (select 1 from public.profiles where id = auth.uid() and role = 'manager')
);

drop policy if exists "orders_insert_own" on public.orders;
create policy "orders_insert_own"
on public.orders for insert
with check (auth.uid() = customer_id);

drop policy if exists "orders_update_own_or_manager" on public.orders;
create policy "orders_update_own_or_manager"
on public.orders for update
using (
  auth.uid() = customer_id
  or exists (select 1 from public.profiles where id = auth.uid() and role = 'manager')
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  customer_id uuid references auth.users(id) on delete cascade,
  name text not null,
  email text,
  phone text not null,
  date date not null,
  time text not null,
  guests integer not null,
  table_number integer,
  special_requests text,
  status text not null default 'Confirmed',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.reservations enable row level security;

drop policy if exists "reservations_select_own_or_manager" on public.reservations;
create policy "reservations_select_own_or_manager"
on public.reservations for select
using (
  auth.uid() = customer_id
  or exists (select 1 from public.profiles where id = auth.uid() and role = 'manager')
);

drop policy if exists "reservations_insert_own" on public.reservations;
create policy "reservations_insert_own"
on public.reservations for insert
with check (auth.uid() = customer_id);

drop policy if exists "reservations_update_own_or_manager" on public.reservations;
create policy "reservations_update_own_or_manager"
on public.reservations for update
using (
  auth.uid() = customer_id
  or exists (select 1 from public.profiles where id = auth.uid() and role = 'manager')
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10, 2) not null,
  category text not null,
  image text,
  available boolean not null default true,
  is_special boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.menu_items enable row level security;

drop policy if exists "menu_public_read" on public.menu_items;
create policy "menu_public_read"
on public.menu_items for select
using (true);

drop policy if exists "menu_manager_write" on public.menu_items;
create policy "menu_manager_write"
on public.menu_items for all
using (exists (select 1 from public.profiles where id = auth.uid() and role = 'manager'))
with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'manager'));

insert into public.menu_items (name, category, description, price, image, available, is_special)
select *
from (values
  ('Achichuk Salad', 'Starters', 'Tomato, cucumber, onion, herbs, and light vinegar dressing', 28000, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd', true, false),
  ('Manti', 'Starters', 'Steamed dumplings filled with lamb, onion, and cumin', 54000, 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c', true, true),
  ('Tashkent Plov', 'Main Course', 'Rice cooked with lamb, carrots, chickpeas, raisins, and quail egg', 78000, 'https://images.unsplash.com/photo-1633945274309-2c16c9682a8c', true, true),
  ('Samsa', 'Main Course', 'Clay-oven pastry filled with diced lamb and onion', 26000, 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec', true, true),
  ('Lagman', 'Main Course', 'Hand-pulled noodles with beef, vegetables, and rich tomato broth', 68000, 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624', true, false),
  ('Lepeshka', 'Breads', 'Traditional Uzbek round bread baked in a tandoor', 12000, 'https://images.unsplash.com/photo-1509440159596-0249088772ff', true, false),
  ('Halva', 'Desserts', 'Nutty sesame halva with pistachio and tea pairing', 34000, 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e', true, true),
  ('Green Tea', 'Drinks', 'Uzbek-style hot green tea served in a piala', 9000, 'https://images.unsplash.com/photo-1544787219-7f47ccb76574', true, false),
  ('Kompot', 'Drinks', 'House fruit drink with apricot, cherry, and apple', 18000, 'https://images.unsplash.com/photo-1544145945-f90425340c7e', true, false)
) as item(name, category, description, price, image, available, is_special)
where not exists (select 1 from public.menu_items);
